### PR TITLE
Retrying for DataIntegrityViolationException in some cases for delete trustbundle after deleting trustAnchor

### PR DESCRIPTION
**Pull request by kshitizdeep1**
Error deleting bundle org.springframework.dao.DataIntegrityViolationException: execute; SQL [DELETE FROM trustbundle WHERE trustbundle.id = ?]; Cannot delete or update a parent row: a foreign key constraint fails (service_instance_db.trustbundleanchor, CONSTRAINT ``XXXXXXXXXXXXX`` FOREIGN KEY (trustBundleId) REFERENCES trustbundle (id));

### CODE REVIEW

**Review by gm2552 — COMMENTED** [review]
@leoclee you will need to review this and take appropriate action

**Comment by kshitizdeep1** [comment]
@gm2552 Hi Greg any suggestion why this behavior is happening I am still not sure without receiving onComplete() signal why it is executing the below Then() and it's happening very few times like 100 to 1

**Comment by leoclee** [comment]
> @leoclee you will need to review this and take appropriate action

@gm2552 Yep, I have been in communication with @kshitizdeep1 on this change.

**Comment by kshitizdeep1** [comment]
please don't merge there is still some issue with these changes.

**Comment by kshitizdeep1** [comment]
Closing this pr for now retryWhen breaking the onErrorResume more analysis required to check why this issue is getting triggered.

**Pull request closed without merging**
